# Site settings
title: Alex Hwang
description: >-
lang: en-US
timezone: Asia/Jakarta
image: assets/img/headshot.jpeg # This image used for Open Graph more info https://ogp.me/
repo: 
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Alex Hwang
  bio: >-
    Physics student playing with light and nanotechnology. <br><br>
    Currently: <a href="https://www.churchillscholarship.org/">Churchill Scholar</a>/MPhil student at 
    <a href="https://www.np.phy.cam.ac.uk/">NanoPhotonics Centre</a>, University of Cambridge.<br><br>
    Previously: B.S. Physics, B.A. Electrical Engineering, <i>summa cum laude</i>, Rice University<br><br>
    Twitter: <a href="https://twitter.com/alexhwang">@alexhwang</a>
  username: username
  email: aykhwang at gmail
  avatar: /assets/img/headshot.jpeg

# Url settings
url: "https://klise.now.sh"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
